#pragma once

#define ENGINE_POINT_LIGHT_BUFFER 1;
#define ENGINE_SPOTLIGHT_LIGHT_BUFFER 2;
#define ENGINE_DIRECTIONAL_LIGHT_BUFFER 3;

#define ENGINE_AMBIENT_TEXTURE 4;
#define ENGINE_DIFFUSE_TEXTURE 5;
#define ENGINE_SPECULAR_TEXTURE 6;
#define ENGINE_EMISSION_TEXTURE 7;
#define ENGINE_NORMAL_TEXTURE 8;
#define ENGINE_UNIVERSAL_TEXTURE 9;